### ISSUE TITLE
In-Class Encoding Groups + Assignments [October]

### ISSUE THREAD

**Issue by cmccraw** [cmccraw/LiliElbe_EngagedLearners#11]
# In-Class Encoding Groups + Assignments

These are the groups with which you will be encoding documents in class throughout the month of October:

- Natasha (@natashaaranda ), John (@meehanjm), Orion (@orionelrod): 
  - Socialdemokraten
---
- Brenda (@btorres34), Susan (@svanderveer), Colin (@coconnell22): 
  - 1933-01-09HoyerSchrembs
---
- Malone (@msimmons5), Melissa (@melezovic), Diosa (@d-bahe):
  - 1932-02-24HarthernSchumann
---
- Megan (@mfries2), Kritika (@kdabral), Mylin (@MylinhLam213):
  - 1932-03-09HoyerSirs
---
- Phylicia (@Phyhall), Molly (@mollykaull), Laura (@lpatriciobellizzi):
  - 1932-07-16HoyerSchumann
---
- Dove (@doverebmann), Maddie (@m-nesbitt), Josh (@jbrockland):
  - 1932-08-11SchumannHoyer

**Comment by natashaaranda** [comment]
@RJP43 I am working on the header for the periodical 1931-11-28socialdemokraten. The author is unknown, is there a key for an unknown author❓ Also what is the format for encoding subheadlines? If the periodical is in question and answer format do you attribute each section to whoever is speaking, and what is the format when the author is unknown?
Thank you
😃

**Comment by RJP43** [comment]
@natashaaranda when an author is unknown simply leave that element out of your encoding. Sometimes in proofing @cmccraw or I will be able to determine the author and add that in the metadata because @emilydatskou or @ProfPLC may know the author and while there might not be a byline on the actual periodical we will still include the information in the metadata.  Such information might also be listed on the LEDA Metadata Spreadsheet. 
  
As for subheadlines - let me clarify the following that can be found under the [periodical (Journal, Magazine, Newspaper Articles) section in the guidelines](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/encodingGuidelines.md#journal-magazine-newspaper-articles):  
  
````
<div rend="headlines">
      <list>
           <item rend="primary"><!--text of main headline--></item>
           <!--additional <item> elements with no @rend attribute value can be used to list sub-headlines-->
      </list>
</div>
````  
so  what I mean by `<!--additional <item> elements with no @rend attribute value can be used to list sub-headlines-->` is `<item>sub headline text goes here</item>`

I am not entirely sure how to answer your other questions but hopefully, by now, you have consulted with @cmccraw or another encoder. When encoding periodicals please  be sure to be referencing [Sanheden.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/encodingExamples/Sanheden.xml) as your example. 👍

**Comment by cmccraw** [comment]
@natashaaranda @orionelrod @meehanjm Take a look at Becca's response, and plan on making any necessary changes to the Socialdemokraten XML document tomorrow in class. Can touch base then if you have any questions!

**Comment by cmccraw** [comment]
@melezovic @kdabral @d-bahe @coconnell22 @JBrockland @orionelrod @msimmons5 @natashaaranda @mfries2 @Phyhall @meehanjm @lpatriciobellizzi @m-nesbitt @doverebmann @svanderveer @btorres34 @mollykaull @MylinhLam213

Date format: 
```<date when="2019-07-06">July 6th, 2019</date>```

**Comment by cmccraw** [comment]
@melezovic @kdabral @d-bahe @coconnell22 @JBrockland @orionelrod @msimmons5 @natashaaranda @mfries2 @Phyhall @meehanjm @lpatriciobellizzi @m-nesbitt @doverebmann @svanderveer @btorres34 @mollykaull @MylinhLam213

Just a note that some of your work is OFFICIALLY on the website!

- _B.T._: http://lilielbe.org/context/periodicals/1931-11-29_BT.html
- _1931-03-06LEKnudsen_: http://lilielbe.org/context/letters/1931-03-06LEKnudsen.html
- _1931-06-27LEGarland_: http://lilielbe.org/context/letters/1931-06-27LEGarland.html
- _1933-01-09HoyerSchrembs_: http://lilielbe.org/context/letters/1933-01-09HoyerSchrembs.html

🎉 🎉 🎉Congrats! 🎉 🎉 🎉
